prd:
  catalog_name: ineszz46
  schema_name: house_prices
acc:
  catalog_name: ineszz46
  schema_name: house_prices
dev:
  catalog_name: ineszz46
  schema_name: house_prices

experiment_name_basic: /Shared/house-prices-basic
experiment_name_custom: /Shared/house-prices-custom

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6


num_features:
  - LotFrontage
  - LotArea
  - OverallQual
  - OverallCond
  - YearBuilt
  - YearRemodAdd
  - MasVnrArea
  - TotalBsmtSF
  - GrLivArea
  - GarageCars

cat_features:
  - MSZoning
  - Street
  - Alley
  - LotShape
  - LandContour
  - Neighborhood
  - Condition1
  - BldgType
  - HouseStyle
  - RoofStyle
  - Exterior1st
  - Exterior2nd
  - MasVnrType
  - Foundation
  - Heating
  - CentralAir
  - SaleType
  - SaleCondition

target: SalePrice
